from __future__ import annotations

import argparse
import shutil
from pathlib import Path

import pandas as pd

from config import (
    DEFAULT_BATCH_SIZE,
    DEFAULT_DATA_DIR,
    DEFAULT_DROPOUT,
    DEFAULT_EPOCHS,
    DEFAULT_GATE_INIT_MEAN,
    DEFAULT_GATE_INIT_STD,
    DEFAULT_GATE_LR_MULTIPLIER,
    DEFAULT_LR,
    DEFAULT_NUM_WORKERS,
    DEFAULT_OUTPUT_DIR,
    DEFAULT_SEED,
    DEFAULT_SWEEP_LAMBDAS,
    DEFAULT_THRESHOLD,
    ensure_output_dirs,
    resolve_path,
)
from train import run_training
from utils import ensure_artifacts_exist, save_json

SWEEP_RESULTS_START = "<!-- SWEEP_RESULTS_START -->"
SWEEP_RESULTS_END = "<!-- SWEEP_RESULTS_END -->"


def _markdown_table(records: list[dict[str, float]]) -> str:
    header = "| Lambda | Test Accuracy | Sparsity Level (%) |"
    separator = "| --- | ---: | ---: |"
    rows = [
        f"| {record['Lambda']:.0e} | {record['Test Accuracy']:.2f} | {record['Sparsity Level (%)']:.2f} |"
        for record in records
    ]
    return "\n".join([header, separator, *rows])


def _write_summary_markdown(summary_path: Path, records: list[dict[str, float]]) -> Path:
    table = _markdown_table(records)
    content = "\n".join(
        [
            "# Sweep Summary",
            "",
            "This file is generated by `python sweep.py` and summarizes the accuracy-sparsity trade-off across lambda values.",
            "",
            table,
            "",
            "The table reports final-epoch accuracy and final-epoch thresholded sparsity. The sweep also writes `outputs/checkpoints/sweep_best.pt` plus `outputs/plots/sweep_best_gate_hist.png` for the best accuracy-selected checkpoint, and `outputs/plots/final_sparse_gate_hist.png` plus `outputs/metrics/final_sparse_summary.json` for the best final sparse endpoint used in presentations.",
        ]
    )
    summary_path.write_text(content + "\n", encoding="utf-8")
    return summary_path


def _update_report_results(report_path: Path, records: list[dict[str, float]]) -> Path:
    report_text = report_path.read_text(encoding="utf-8")
    start_index = report_text.find(SWEEP_RESULTS_START)
    end_index = report_text.find(SWEEP_RESULTS_END)
    if start_index == -1 or end_index == -1 or start_index > end_index:
        raise ValueError("Report file does not contain a valid sweep results block.")

    table = _markdown_table(records)
    replacement = f"{SWEEP_RESULTS_START}\n{table}\n{SWEEP_RESULTS_END}"
    updated = report_text[:start_index] + replacement + report_text[end_index + len(SWEEP_RESULTS_END) :]
    report_path.write_text(updated, encoding="utf-8")
    return report_path


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run a lambda sweep for the self-pruning MLP.")
    parser.add_argument("--lambdas", type=float, nargs="+", default=DEFAULT_SWEEP_LAMBDAS, help="Lambda values to evaluate.")
    parser.add_argument("--epochs", type=int, default=DEFAULT_EPOCHS, help="Number of training epochs per run.")
    parser.add_argument("--batch-size", type=int, default=DEFAULT_BATCH_SIZE, help="Mini-batch size.")
    parser.add_argument("--lr", type=float, default=DEFAULT_LR, help="Learning rate for Adam.")
    parser.add_argument("--dropout", type=float, default=DEFAULT_DROPOUT, help="Dropout probability.")
    parser.add_argument("--gate-init-mean", type=float, default=DEFAULT_GATE_INIT_MEAN, help="Mean for gate score initialization.")
    parser.add_argument("--gate-init-std", type=float, default=DEFAULT_GATE_INIT_STD, help="Std for gate score initialization.")
    parser.add_argument("--gate-lr-multiplier", type=float, default=DEFAULT_GATE_LR_MULTIPLIER, help="Multiplier for the gate score learning rate.")
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED, help="Deterministic seed for the sweep.")
    parser.add_argument("--quick", action="store_true", help="Run with reduced train/test subsets for smoke tests.")
    parser.add_argument("--train-subset", type=int, default=None, help="Optional train subset size.")
    parser.add_argument("--test-subset", type=int, default=None, help="Optional test subset size.")
    parser.add_argument("--num-workers", type=int, default=DEFAULT_NUM_WORKERS, help="Number of dataloader workers.")
    parser.add_argument("--threshold", type=float, default=DEFAULT_THRESHOLD, help="Gate threshold for sparsity reporting.")
    parser.add_argument("--data-dir", type=Path, default=DEFAULT_DATA_DIR, help="Dataset directory.")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR, help="Artifact output directory.")
    parser.add_argument(
        "--device",
        type=str,
        default="auto",
        help="Device to use: auto, cpu, cuda, or any torch device string.",
    )
    return parser


def main() -> None:
    args = build_arg_parser().parse_args()
    output_paths = ensure_output_dirs(resolve_path(args.output_dir))
    report_path = resolve_path(Path("report") / "report.md")

    sweep_results: list[dict[str, float]] = []
    detailed_runs: list[dict[str, object]] = []
    best_accuracy_run: dict[str, object] | None = None
    best_final_run: dict[str, object] | None = None

    for lambda_sparsity in args.lambdas:
        print(f"Running sweep for lambda={lambda_sparsity:.0e}")
        run_result = run_training(
            lambda_sparsity=lambda_sparsity,
            epochs=args.epochs,
            batch_size=args.batch_size,
            lr=args.lr,
            dropout=args.dropout,
            gate_init_mean=args.gate_init_mean,
            gate_init_std=args.gate_init_std,
            gate_lr_multiplier=args.gate_lr_multiplier,
            seed=args.seed,
            device=args.device,
            data_dir=resolve_path(args.data_dir),
            output_dir=resolve_path(args.output_dir),
            threshold=args.threshold,
            quick=args.quick,
            train_subset=args.train_subset,
            test_subset=args.test_subset,
            num_workers=args.num_workers,
            save_aliases=False,
            download=True,
        )

        row = {
            "Lambda": float(lambda_sparsity),
            "Test Accuracy": float(run_result["final_test_accuracy"]),
            "Sparsity Level (%)": float(run_result["final_sparsity_percentage"]),
        }
        sweep_results.append(row)
        detailed_runs.append(run_result)

        if best_accuracy_run is None or float(run_result["best_test_accuracy"]) > float(best_accuracy_run["best_test_accuracy"]):
            best_accuracy_run = run_result

        if best_final_run is None or float(run_result["final_test_accuracy"]) > float(best_final_run["final_test_accuracy"]):
            best_final_run = run_result

    results_csv_path = output_paths["root"] / "results.csv"
    summary_md_path = output_paths["root"] / "summary.md"
    detailed_json_path = output_paths["sweeps"] / "sweep_results.json"

    pd.DataFrame(sweep_results).to_csv(results_csv_path, index=False)
    _write_summary_markdown(summary_md_path, sweep_results)
    _update_report_results(report_path, sweep_results)
    save_json(
        detailed_json_path,
        [
            {
                "lambda_sparsity": float(run["lambda_sparsity"]),
                "best_test_accuracy": float(run["best_test_accuracy"]),
                "best_sparsity_percentage": float(run["best_sparsity_percentage"]),
                "final_test_accuracy": float(run["final_test_accuracy"]),
                "final_sparsity_percentage": float(run["final_sparsity_percentage"]),
                "checkpoint_path": str(run["checkpoint_path"]),
                "best_histogram_path": str(run["histogram_path"]),
                "final_histogram_path": str(run["final_histogram_path"]),
                "final_summary_path": str(run["final_summary_path"]),
            }
            for run in detailed_runs
        ],
    )

    if best_accuracy_run is not None:
        sweep_best_checkpoint = output_paths["checkpoints"] / "sweep_best.pt"
        sweep_best_histogram = output_paths["plots"] / "sweep_best_gate_hist.png"
        shutil.copy2(best_accuracy_run["checkpoint_path"], sweep_best_checkpoint)
        shutil.copy2(best_accuracy_run["histogram_path"], sweep_best_histogram)

    if best_final_run is not None:
        final_sparse_histogram = output_paths["plots"] / "final_sparse_gate_hist.png"
        final_sparse_summary = output_paths["metrics"] / "final_sparse_summary.json"
        shutil.copy2(best_final_run["final_histogram_path"], final_sparse_histogram)
        shutil.copy2(best_final_run["final_summary_path"], final_sparse_summary)

    if best_accuracy_run is not None and best_final_run is not None:
        ensure_artifacts_exist([sweep_best_checkpoint, sweep_best_histogram, final_sparse_histogram, final_sparse_summary])

    ensure_artifacts_exist([results_csv_path, summary_md_path, report_path, detailed_json_path])
    print(f"Sweep results saved to: {results_csv_path}")
    print(f"Markdown summary saved to: {summary_md_path}")
    print(f"Report updated at: {report_path}")


if __name__ == "__main__":
    main()
